[package]
edition = "2024"
name = "ui-composer-input"
version = "0.1.0"

[lib]
name = "ui_composer_input"
# crate-type = ["dylib"]

[features]
default = []
std = []

[dependencies]
smol_str = "0.3.5"
vek = "0.17.2"
nstr = "0.3.2"
