[package]
name = "example-android"
version = "0.1.0"
edition = "2024"

[lib]
name = "example_android"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
log = "0.4"
android_logger = "0.13"
android-activity = { version = "0.5", features = ["native-activity"] }
